todo/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"   

urlpatterns = [
		path('', views.index, name="list"),
		
		path("register/", views.register_request, name="register"),
		path("login/", views.login_request, name="login"),
		path("logout/", views.logout_request, name= "logout"),
		path('update_task/<str:pk>/', views.updateTask, name="update_task"),
		path('delete/<str:pk>/', views.deleteTask, name="delete"),
		
		

]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),

]


todo/tasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
	title = models.CharField(max_length=200)
	complete = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

todo/tasks/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user


class TaskForm(forms.ModelForm):
	title= forms.CharField(widget= forms.TextInput(attrs={'placeholder':'Add new task...'}))

	class Meta:
		model = Task
		fields = '__all__'



		

todo/tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

from .models import *
from .forms import *

# Create your views here.


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("tasks:list")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="tasks/register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("tasks:list")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="tasks/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("tasks:list")	

def index(request):
	tasks = Task.objects.all()

	form = TaskForm()

	if request.method =='POST':
		form = TaskForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('/')


	context = {'tasks':tasks, 'form':form}
	return render(request, 'tasks/list.html', context)

def updateTask(request, pk):
	task = Task.objects.get(id=pk)

	form = TaskForm(instance=task)

	if request.method == 'POST':
		form = TaskForm(request.POST, instance=task)
		if form.is_valid():
			form.save()
			return redirect('/')

	context = {'form':form}

	return render(request, 'tasks/update_task.html', context)

def deleteTask(request, pk):
	item = Task.objects.get(id=pk)

	if request.method == 'POST':
		item.delete()
		return redirect('/')

	context = {'item':item}
	return render(request, 'tasks/delete.html', context)



todo/tasks/templates/tasks/delete.html

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>To Do</title>
  </head>
  <body>


	<style type="text/css">
		body{
		  background-color:#3f1052;
		}
		
		
	  </style>


	<div class="container-fluid">
    	<div class="row">
			<div class="col-lg-12"; style=" height: 50px;"></div>
			<div class="col-lg-3";></div>
			<div class="col-lg-6";>	
				<center>
				<div class="jumbotron" style="background-color: #3f1052; color: white;">
					<p>Delete "{{item}}"?</p>

					<a href="{% url 'tasks:list' %}" >Cancel</a>
					
					<form method="POST" action="">
						{% csrf_token %}
						<input type="submit" name="Confirm">
					</form>					
				</div>
				</center>
			</div>
			<div class="col-lg-3";></div>
		</div>
	</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>

todo/tasks/templates/tasks/header.html
<!DOCTYPE html>
<html>
  <head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!--Bootstrap CSS-->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 <title>Title</title>
  </head>
 <body>

    {% block content %}

    {% endblock %} 
      
  </body>
</html>

todo/tasks/templates/tasks/list.html

<!doctype html>
<html lang="en">
  <head>

   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!--Bootstrap CSS-->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>To Do</title>
  </head>
  <body>


	<style type="text/css">
		body{
		  background-color:#3f1052;
		}
		
		
	  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">ToDoApp</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarText">
	  <ul class="navbar-nav mr-auto">
		{% if user.is_authenticated %}
		
		<li class="nav-item">
		  <a class="nav-link" href="/logout">Logout</a>
		</li>
		<li class="nav-item" style="padding-left: 50px;">
		  <a class="nav-link" href="#">Welcome, {{user.username}}</a>
		</li>
  
		{% else %}
  
		<li class="nav-item">
		  <a class="nav-link" href="/login">Login</a>
		</li>
  
		{% endif %}
	  </ul>
	</div>
  </nav>


	
	<div class="container-fluid">
		
		

    	<div class="row">
			<div class="col-lg-12"; style=" height: 50px;"></div>
			<div class="col-lg-3";></div>
			<div class="col-lg-6">
				<center>
					<h1 class="display-4" style="color: white;">To Do List</h1>

					<form method="POST" action="/" >
						{% csrf_token %}
						{{form.title}}	
						<input class="btn btn-info" type="submit" name="Create Task" >
					</form>
					
				</center>
			</div>
			<div class="col-lg-3";></div>
			<div class="col-lg-12"; style=" height: 50px;"></div>
			<div class="col-lg-3";></div>
			<div class="col-lg-6";>	
				<center>
				<div class="jumbotron" style="background-color: #3f1052; color: white;">
					 
						
							{% for task in tasks %}
						<div class="item-row">

							{% if task.complete == True %}
							<strike>{{task}}</strike>
							{% else %}
							<span>{{task}}</span>
							{% endif %}

							
							<a class="btn btn-sm btn-danger" href="{% url 'tasks:delete' task.id %}">Delete</a>
							<a class="btn btn-sm btn-info" href="{% url 'tasks:update_task' task.id %}" style="margin: 10px;">Update</a>
						</div>
					{% endfor %}
						
						</p>
					</form>
				  </div>
				</center>
			</div>
			<div class="col-lg-3";></div>
		</div>
	</div>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>

todo/tasks/templates/tasks/login.html
{% extends "tasks/header.html" %}

{% block content %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

todo/tasks/templates/tasks/register.html
{% extends "tasks/header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

todo/tasks/templates/tasks/update_task.html

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>To Do</title>
  </head>
  <body>


	<style type="text/css">
		body{
		  background-color:#3f1052;
		}
		
		
	  </style>


	<div class="container-fluid">
    	<div class="row">
			<div class="col-lg-12"; style=" height: 50px;"></div>
			<div class="col-lg-3";></div>
			<div class="col-lg-6";>	
				<center>
					<h2 style="color: white;">Update</h2>

					<form method="POST" action="" style="color: white;">
						{% csrf_token %}
					
						{{form}}
						<input type="submit" name="Update Task">
						
						
					</form>
				</center>
			</div>
			<div class="col-lg-3";></div>
		</div>
	</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>